--- # required, replace with your own information -----
# _config.yml

title: Claudio Fanconi
author: Claudio Fanconi
description: >
  Personal webpage of Claudio Fanconi
baseurl: "fanconic.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
